### ISSUE TITLE
Unable to connect to ProxyFleet

### ISSUE THREAD

**Issue by kanya-approve** [jeremylvln/Shulker#194]
Manifests
```
apiVersion: shulkermc.io/v1alpha1
kind: MinecraftCluster
metadata:
  name: shulker
  namespace: apps
spec: {}
```
```
apiVersion: shulkermc.io/v1alpha1
kind: ProxyFleet
metadata:
  name: shulker
  namespace: apps
spec:
  clusterRef:
    name: shulker
  replicas: 1
  service:
    type: ClusterIP
  template:
    spec:
      config: 
        proxyProtocol: true 
      version:
        channel: Velocity
        name: latest
```

**What's the issue**: When trying to connect to the ProxyFleet with `kubectl port-forward service/shulker :25565 -n apps -v=6`, it times out.

**Expected behavior**: Being able to connect.

Logs are attached.

### What components are involved in your issue?

Proxy Agent (Velocity)

### Version

0.3.0

### Kubernetes Version

1.27.4

### Relevant log output

```Shell
{"ctlConf":{"GameServerName":"shulker-px8hh-9xgth","PodNamespace":"apps","Address":"localhost","IsLocal":false,"LocalFile":"","Delay":0,"Timeout":0,"Test":"","TestSdkName":"","KubeConfig":"","GracefulTermination":true,"GRPCPort":9357,"HTTPPort":9358},"featureGates":"CountsAndLists=false\u0026Example=false\u0026FleetAllocationOverflow=false\u0026PlayerAllocationFilter=false\u0026PlayerTracking=false\u0026PodHostname=true\u0026ResetMetricsOnDelete=true\u0026SplitControllerAndExtensions=true","message":"Starting sdk sidecar","severity":"info","source":"main","time":"2023-11-02T09:53:48.929110116Z","version":"1.35.0"}
W1102 09:53:48.929374       1 client_config.go:618] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
{"gsKey":"apps/shulker-px8hh-9xgth","message":"Created GameServer sidecar","severity":"info","source":"*sdkserver.SDKServer","time":"2023-11-02T09:53:48.930030156Z"}
{"gsKey":"apps/shulker-px8hh-9xgth","message":"Connection to Kubernetes service established","severity":"info","source":"*sdkserver.SDKServer","time":"2023-11-02T09:53:48.943769994Z","try":0}
{"grpcEndpoint":"localhost:9357","message":"Starting SDKServer grpc service...","severity":"info","source":"main","time":"2023-11-02T09:53:48.944445234Z"}
{"httpEndpoint":"localhost:9358","message":"Starting SDKServer grpc-gateway...","severity":"info","source":"main","time":"2023-11-02T09:53:48.945295834Z"}
[init] Resolving type given VELOCITY
{"gsKey":"apps/shulker-px8hh-9xgth","message":"Starting workers...","queue":"agones.dev.apps.shulker-px8hh-9xgth","severity":"info","source":"*sdkserver.SDKServer","time":"2023-11-02T09:53:49.045083104Z","workers":1}
[init] Downloading https://papermc.io/api/v2/projects/velocity/versions/3.2.0-SNAPSHOT/builds/294/downloads/velocity-3.2.0-SNAPSHOT-294.jar
[mc-image-helper] 09:53:53.068 INFO  : Downloaded /server/velocity-3.2.0-SNAPSHOT-294.jar
[init] Setting initial memory to 512m and max to 512m
WARN StatusConsoleListener Advanced terminal features are not available in this environment
[09:53:54 INFO]: Booting up Velocity 3.2.0-SNAPSHOT (git-8dcc7ee3-b294)...
[09:53:54 INFO]: Loading localizations...
[09:53:54 INFO]: Connections will use epoll channels, libdeflate (Linux aarch64) compression, OpenSSL 1.1.x (Linux aarch64) ciphers
[09:53:54 INFO]: Loading plugins...
[09:53:54 INFO]: Loaded plugin shulker-proxy-agent 0.3.0 by Jérémy Levilain <jeremy@jeremylvln.fr>
[09:53:54 INFO]: Loaded 1 plugins
[09:53:55 INFO] [io.shulkermc.proxyagent.velocity.ShulkerProxyAgentVelocity]: Identified Shulker proxy: apps/shulker-px8hh-9xgth
[09:53:55 INFO] [io.shulkermc.proxyagent.velocity.ShulkerProxyAgentVelocity]: Proxy will be force stopped in 86400 seconds
[09:53:55 INFO] [io.shulkermc.proxyagent.velocity.ShulkerProxyAgentVelocity]: Lost proxy will be purged every 1 minutes
[09:53:55 INFO]: Listening on /0.0.0.0:25577
[09:53:55 INFO]: Velocity and some of its plugins collect metrics and send them to bStats (https://bStats.org).
[09:53:55 INFO]: bStats collects some basic information for plugin authors, like how many people use
[09:53:55 INFO]: their plugin and their total player count. It's recommended to keep bStats enabled, but
[09:53:55 INFO]: if you're not comfortable with this, you can opt-out by editing the config.txt file in
[09:53:55 INFO]: the '/plugins/bStats/' folder and setting enabled to false.
[09:53:55 INFO]: Done (2.09s)!
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jeremylvln** [comment]
Do not use the `proxyProtocol` if you are not using a `LoadBalancer` which supports it (most cloud providers does, but definitely not when doing a port-forward). It should solve your issue :)

_(it took me 2 days of debugging the same issue on my test cluster 😭)_

**Comment by kanya-approve** [comment]
How can I resolve this then?

<img width="932" alt="image" src="https://github.com/jeremylvln/Shulker/assets/6502571/cf799006-f87d-43d4-ad9f-a0e3fa1612e2">

**Comment by jeremylvln** [comment]
I never encountered this error before, but after some googling it seems to be a generic error from the launcher and not the server itself. Are you able to connect to another server? Like Hypixel or something like that? You'll probably have the same error.

As this is more a client issue than a server one, it probably have nothing to do with Shulker unfortunately.

**Comment by kanya-approve** [comment]
I'm able to connect to mc.hypixel.net from my client.

**Comment by jeremylvln** [comment]
Okay I found out that I configure Velocity to reject proxies connections (Velocity will compare the IP you used to connect to authenticate in the launcher and the IP you are trying to connect to the server - if its not the same the connection is rejected). But when you are using a port-forward, the proxy will see you with a local IP - definitely not the one you used to authenticate.

I have a "fix" in mind for this, for the time being, you can use a `NodePort` service in your `ProxyFleet` and connect to that directly

**Comment by jeremylvln** [comment]
I've pushed a fix on `main` that will allow proxy connections when no `service` is configured for a `ProxyFleet` or if it is of type `ClusterIP` (but are kept rejected if `LoadBalancer` or `NodePort`). That should solve your issue.

Thanks for pointing out :)

**Comment by jeremylvln** [comment]
Fixed by e8a4993

**Comment by kanya-approve** [comment]
Should I be using next or stable?

**Comment by kanya-approve** [comment]
I've got a new error now.

<img width="621" alt="image" src="https://github.com/jeremylvln/Shulker/assets/6502571/a161cc46-ba3a-4ce8-919d-a006ee9150c7">

**Comment by jeremylvln** [comment]
I never tested a Folia server, did you tag correctly your `MinecraftServer` or `MinecraftServerFleet` with the tag `limbo` or `lobby`? Do you have some logs in Folia? Do you see the logs in the proxy about the registering of your server when it is ready?

**Comment by kanya-approve** [comment]
Actually, I see that the lobby that I created keeps shutting down after about 30 seconds. I'll try to get some logs for why.

**Comment by jeremylvln** [comment]
You can try scaling down Agones to 0 after the pod is created and before it crashes, so it won't be deleted and you'll hopefully have the logs

**Comment by kanya-approve** [comment]
```Shell
[init] Running as uid=1000 gid=1000 with /data as 'drwxrwxrwx 2 0 0 4096 Nov  3 08:53 /data'
[init] Resolving type given PAPER
[mc-image-helper] 08:54:00.465 ERROR : 'install-paper' command failed. Version is 1.35.3
reactor.core.Exceptions$ReactiveException: io.netty.resolver.dns.DnsResolveContext$SearchDomainUnknownHostException: Failed to resolve 'api.papermc.io' [A(1)] and search domain query for configured domains failed as well: [apps.svc.cluster.local, svc.cluster.local, cluster.local, us-central1-f.c.multi-cloud-36e1.internal, c.multi-cloud-36e1.internal, google.internal]
	at reactor.core.Exceptions.propagate(Exceptions.java:408)
	at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:101)
	at reactor.core.publisher.Mono.block(Mono.java:1712)
	at me.itzg.helpers.paper.InstallPaperCommand.useCoordinates(InstallPaperCommand.java:152)
	at me.itzg.helpers.paper.InstallPaperCommand.call(InstallPaperCommand.java:109)
	at me.itzg.helpers.paper.InstallPaperCommand.call(InstallPaperCommand.java:35)
	at picocli.CommandLine.executeUserObject(CommandLine.java:2041)
	at picocli.CommandLine.access$1500(CommandLine.java:148)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
	at picocli.CommandLine.execute(CommandLine.java:2170)
	at me.itzg.helpers.McImageHelper.main(McImageHelper.java:155)
	Suppressed: java.lang.Exception: #block terminated with an error
		at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:103)
		... 13 common frames omitted
Caused by: io.netty.resolver.dns.DnsResolveContext$SearchDomainUnknownHostException: Failed to resolve 'api.papermc.io' [A(1)] and search domain query for configured domains failed as well: [apps.svc.cluster.local, svc.cluster.local, cluster.local, us-central1-f.c.multi-cloud-36e1.internal, c.multi-cloud-36e1.internal, google.internal]
	at io.netty.resolver.dns.DnsResolveContext.finishResolve(DnsResolveContext.java:1097)
	at io.netty.resolver.dns.DnsResolveContext.tryToFinishResolve(DnsResolveContext.java:1044)
	at io.netty.resolver.dns.DnsResolveContext.query(DnsResolveContext.java:432)
	at io.netty.resolver.dns.DnsResolveContext.access$700(DnsResolveContext.java:66)
	at io.netty.resolver.dns.DnsResolveContext$2.operationComplete(DnsResolveContext.java:500)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:590)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:583)
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:559)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:492)
	at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:636)
	at io.netty.util.concurrent.DefaultPromise.setFailure0(DefaultPromise.java:629)
	at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:118)
	at io.netty.resolver.dns.DnsQueryContext.finishFailure(DnsQueryContext.java:348)
	at io.netty.resolver.dns.DnsQueryContext$5.run(DnsQueryContext.java:290)
	at io.netty.util.concurrent.PromiseTask.runTask(PromiseTask.java:98)
	at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:153)
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: io.netty.resolver.dns.DnsNameResolverTimeoutException: [31372: /192.168.64.10:53] DefaultDnsQuestion(api.papermc.io.cluster.local. IN A) query '31372' via UDP timed out after 5000 milliseconds (no stack trace available)
[init] ERROR: failed to download paper
```

**Comment by jeremylvln** [comment]
It seems to be an issue with your cluster and not Shulker directly. Ensure that DNS and internet connectivity works as expected, especially with the Paper API that is failing.

I'm closing this issue as the proxy problem is fixed, open another one if there is an issue with Folia
