### ISSUE TITLE
Redis credentials not being pulled from secret

### ISSUE THREAD

**Issue by kanya-approve** [jeremylvln/Shulker#205]
### What happened?

I've created a MinecraftCluster with Redis cluster credentials, but the proxy crashes with the error message "redis.clients.jedis.exceptions.JedisDataException: NOAUTH Authentication required".

```yaml
apiVersion: v1
kind: Secret
metadata:
  name: redis-secret
type: Opaque
stringData:
  username: REDACTED
  password: REDACTED
```

```yaml
apiVersion: shulkermc.io/v1alpha1
kind: MinecraftCluster
metadata:
  name: shulker
spec:
  networkAdmins:
    - REDACTED
  redis:
    provided:
      credentialsSecretName: redis-secret
      host: REDACTED
      port: REDACTED
    type: Provided
```

### What components are involved in your issue?

Proxy Agent (Velocity)

### Version

0.3.0

### Kubernetes Version

1.27

### Relevant log output

```Shell
[13:38:09 INFO] [io.shulkermc.proxyagent.velocity.ShulkerProxyAgentVelocity]: Identified Shulker proxy: apps/shulker-kmcvb-lcngh
[13:38:09 ERROR] [io.shulkermc.proxyagent.velocity.ShulkerProxyAgentVelocity]: Failed to parse configuration
[13:38:09 ERROR]: redis.clients.jedis.exceptions.JedisDataException: NOAUTH Authentication required.
[13:38:09 ERROR]: 	at redis.clients.jedis.Protocol.processError(Protocol.java:105)
[13:38:09 ERROR]: 	at redis.clients.jedis.Protocol.process(Protocol.java:162)
[13:38:09 ERROR]: 	at redis.clients.jedis.Protocol.read(Protocol.java:221)
[13:38:09 ERROR]: 	at redis.clients.jedis.Connection.readProtocolWithCheckingBroken(Connection.java:351)
[13:38:09 ERROR]: 	at redis.clients.jedis.Connection.getStatusCodeReply(Connection.java:269)
[13:38:09 ERROR]: 	at redis.clients.jedis.Jedis.ping(Jedis.java:339)
[13:38:09 ERROR]: 	at io.shulkermc.proxyagent.ShulkerProxyAgentCommon.onProxyInitialization(ShulkerProxyAgentCommon.kt:57)
[13:38:09 ERROR]: 	at io.shulkermc.proxyagent.velocity.ShulkerProxyAgentVelocity.onProxyInitialization(ShulkerProxyAgentVelocity.kt:30)
[13:38:09 ERROR]: 	at io.shulkermc.proxyagent.velocity.Lmbda$1.execute(Unknown Source)
[13:38:09 ERROR]: 	at com.velocitypowered.proxy.event.UntargetedEventHandler$VoidHandler.lambda$buildHandler$0(UntargetedEventHandler.java:56)
[13:38:09 ERROR]: 	at com.velocitypowered.proxy.event.VelocityEventManager.fire(VelocityEventManager.java:597)
[13:38:09 ERROR]: 	at com.velocitypowered.proxy.event.VelocityEventManager.lambda$fire$5(VelocityEventManager.java:478)
[13:38:09 ERROR]: 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[13:38:09 ERROR]: 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[13:38:09 ERROR]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[13:38:09 ERROR] [io.shulkermc.proxyagent.velocity.ShulkerProxyAgentVelocity]: Failed to ask Agones sidecar to shutdown properly, stopping process manually
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jeremylvln** [comment]
Do you see the `SHULKER_PROXY_REDIS_USERNAME` and `SHULKER_PROXY_REDIS_PASSWORD` environment keys on your proxy pods? I'm currently writing tests on Redis-related code but I'm not finding anything. I may need to create a Redis and test myself

**Comment by jeremylvln** [comment]
I think I found the issue, I messed up with the code! Sorry! I'm publishing a fix, you'll just have to restart your proxies! I'll publish a real release later in the week
