### ISSUE TITLE
ShulkerServerAgent causes Paper MinecraftServerFleet to crash

### ISSUE THREAD

**Issue by kanya-approve** [jeremylvln/Shulker#219]
### What happened?

MinecraftServerFleet created vanilla server fails due to the error below

```yaml
apiVersion: shulkermc.io/v1alpha1
kind: MinecraftServerFleet
metadata:
  name: vanilla
spec:
  clusterRef:
    name: shulker
  replicas: 1
  template:
    spec:
      clusterRef:
        name: shulker
      tags:
        - limbo
        - lobby
        - vanilla
      version:
        channel: Paper
        name: '1.20.2'
      config: {}
```

### What components are involved in your issue?

Server Agent (Paper)

### Version

0.3.0

### Kubernetes Version

1.27

### Relevant log output

```Shell
[init] Starting the Minecraft server...
Downloading mojang_1.20.2.jar
Applying patches
Starting org.bukkit.craftbukkit.Main
System Info: Java 17 (OpenJDK 64-Bit Server VM 17.0.8.1+1) Host: Linux 5.15.120+ (aarch64)
Loading libraries, please wait...
2023-11-10 23:24:15,355 ServerMain WARN Advanced terminal features are not available in this environment
[23:24:19 INFO]: Environment: Environment[accountsHost=https://api.mojang.com, sessionHost=https://sessionserver.mojang.com, servicesHost=https://api.minecraftservices.com, name=PROD]
[23:24:20 INFO]: Found new data pack file/bukkit, loading it automatically
[23:24:21 INFO]: Loaded 7 recipes
[23:24:22 INFO]: Starting minecraft server version 1.20.2
[23:24:22 INFO]: Loading properties
[23:24:22 INFO]: This server is running Paper version git-Paper-280 (MC: 1.20.2) (Implementing API version 1.20.2-R0.1-SNAPSHOT) (Git: 4675152)
[23:24:22 INFO]: Server Ping Player Sample Count: 12
[23:24:22 INFO]: Using 4 threads for Netty based IO
[23:24:22 INFO]: [ChunkTaskScheduler] Chunk system is using 1 I/O threads, 1 worker threads, and gen parallelism of 1 threads
[23:24:22 WARN]: [!] The timings profiler has been enabled but has been scheduled for removal from Paper in the future.
    We recommend installing the spark profiler as a replacement: https://spark.lucko.me/
    For more information please visit: https://github.com/PaperMC/Paper/issues/8948
[23:24:23 INFO]: Default game type: SURVIVAL
[23:24:23 INFO]: Generating keypair
[23:24:23 INFO]: Starting Minecraft server on *:25565
[23:24:23 INFO]: Using epoll channel type
[23:24:23 INFO]: Paper: Using libdeflate (Linux aarch64) compression from Velocity.
[23:24:23 INFO]: Paper: Using OpenSSL 1.1.x (Linux aarch64) cipher from Velocity.
[23:24:23 INFO]: [ShulkerServerAgent] Loading server plugin ShulkerServerAgent v0.3.0
[23:24:23 WARN]: **** SERVER IS RUNNING IN OFFLINE/INSECURE MODE!
[23:24:23 WARN]: The server will make no attempt to authenticate usernames. Beware.
[23:24:23 WARN]: Whilst this makes it possible to use Velocity, unless access to your server is properly restricted, it also opens up the ability for hackers to connect with any username they choose.
[23:24:23 WARN]: Please see https://docs.papermc.io/velocity/security for further information.
[23:24:23 WARN]: To change this, set "online-mode" to "true" in the server.properties file.
[23:24:23 INFO]: Preparing level "world"
[23:24:35 INFO]: Preparing start region for dimension minecraft:overworld
[23:24:35 INFO]: Time elapsed: 141 ms
[23:24:35 INFO]: [ShulkerServerAgent] Enabling ShulkerServerAgent v0.3.0
[23:24:36 ERROR]: [ShulkerServerAgent] Failed to parse configuration: io.grpc.StatusRuntimeException: CANCELLED: Failed to read message.
[23:24:36 WARN]: java.util.concurrent.ExecutionException: io.grpc.StatusRuntimeException: CANCELLED: Failed to read message.
[23:24:36 WARN]: 	at java.base/java.util.concurrent.CompletableFuture.reportGet(Unknown Source)
[23:24:36 WARN]: 	at java.base/java.util.concurrent.CompletableFuture.get(Unknown Source)
[23:24:36 WARN]: 	at shulker-server-agent-0.3.0-paper.jar//io.shulkermc.serveragent.ShulkerServerAgentCommon.onServerInitialization(ShulkerServerAgentCommon.kt:28)
[23:24:36 WARN]: 	at shulker-server-agent-0.3.0-paper.jar//io.shulkermc.serveragent.paper.ShulkerServerAgentPaper.onEnable(ShulkerServerAgentPaper.kt:11)
[23:24:36 WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281)
[23:24:36 WARN]: 	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:189)
[23:24:36 WARN]: 	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104)
[23:24:36 WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507)
[23:24:36 WARN]: 	at org.bukkit.craftbukkit.v1_20_R2.CraftServer.enablePlugin(CraftServer.java:644)
[23:24:36 WARN]: 	at org.bukkit.craftbukkit.v1_20_R2.CraftServer.enablePlugins(CraftServer.java:555)
[23:24:36 WARN]: 	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:627)
[23:24:36 WARN]: 	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:424)
[23:24:36 WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:308)
[23:24:36 WARN]: 	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1086)
[23:24:36 WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315)
[23:24:36 WARN]: 	at java.base/java.lang.Thread.run(Unknown Source)
[23:24:36 WARN]: Caused by: io.grpc.StatusRuntimeException: CANCELLED: Failed to read message.
[23:24:36 WARN]: 	at shulker-server-agent-0.3.0-paper.jar//io.grpc.Status.asRuntimeException(Status.java:537)
[23:24:36 WARN]: 	at shulker-server-agent-0.3.0-paper.jar//io.grpc.stub.ClientCalls$UnaryStreamToFuture.onClose(ClientCalls.java:538)
[23:24:36 WARN]: 	at shulker-server-agent-0.3.0-paper.jar//io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:574)
[23:24:36 WARN]: 	at shulker-server-agent-0.3.0-paper.jar//io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:72)
[23:24:36 WARN]: 	at shulker-server-agent-0.3.0-paper.jar//io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInternal(ClientCallImpl.java:742)
[23:24:36 WARN]: 	at shulker-server-agent-0.3.0-paper.jar//io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:723)
[23:24:36 WARN]: 	at shulker-server-agent-0.3.0-paper.jar//io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
[23:24:36 WARN]: 	at shulker-server-agent-0.3.0-paper.jar//io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:133)
[23:24:36 WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[23:24:36 WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[23:24:36 WARN]: 	... 1 more
[23:24:36 WARN]: Caused by: java.lang.VerifyError: Bad return type
[23:24:36 WARN]: Exception Details:
[23:24:36 WARN]:   Location:
[23:24:36 WARN]:     dev/agones/dev/sdk/GameServer$ObjectMeta.internalGetMapFieldReflection(I)Lcom/google/protobuf/MapFieldReflectionAccessor; @32: areturn
[23:24:36 WARN]:   Reason:
[23:24:36 WARN]:     Type 'com/google/protobuf/MapField' (current frame, stack[0]) is not assignable to 'com/google/protobuf/MapFieldReflectionAccessor' (from method signature)
[23:24:36 WARN]:   Current Frame:
[23:24:36 WARN]:     bci: @32
[23:24:36 WARN]:     flags: { }
[23:24:36 WARN]:     locals: { 'dev/agones/dev/sdk/GameServer$ObjectMeta', integer }
[23:24:36 WARN]:     stack: { 'com/google/protobuf/MapField' }
[23:24:36 WARN]:   Bytecode:
[23:24:36 WARN]:     0000000: 1bab 0000 0000 0025 0000 0002 0000 0008
[23:24:36 WARN]:     0000010: 0000 001b 0000 0009 0000 0020 2ab6 0034
[23:24:36 WARN]:     0000020: b02a b600 38b0 bb00 3b59 1bba 003d 0000
[23:24:36 WARN]:     0000030: b700 41bf                              
[23:24:36 WARN]:   Stackmap Table:
[23:24:36 WARN]:     same_frame(@28)
[23:24:36 WARN]:     same_frame(@33)
[23:24:36 WARN]:     same_frame(@38)
[23:24:36 WARN]: 
[23:24:36 WARN]: 	at shulker-server-agent-0.3.0-paper.jar//dev.agones.dev.sdk.GameServer$Builder.getObjectMeta(GameServer.java:8581)
[23:24:36 WARN]: 	at shulker-server-agent-0.3.0-paper.jar//dev.agones.dev.sdk.GameServer$Builder.getObjectMetaFieldBuilder(GameServer.java:8678)
[23:24:36 WARN]: 	at shulker-server-agent-0.3.0-paper.jar//dev.agones.dev.sdk.GameServer$Builder.mergeFrom(GameServer.java:8529)
[23:24:36 WARN]: 	at shulker-server-agent-0.3.0-paper.jar//dev.agones.dev.sdk.GameServer$1.parsePartialFrom(GameServer.java:8962)
[23:24:36 WARN]: 	at shulker-server-agent-0.3.0-paper.jar//dev.agones.dev.sdk.GameServer$1.parsePartialFrom(GameServer.java:8954)
[23:24:36 WARN]: 	at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:86)
[23:24:36 WARN]: 	at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:48)
[23:24:36 WARN]: 	at shulker-server-agent-0.3.0-paper.jar//io.grpc.protobuf.lite.ProtoLiteUtils$MessageMarshaller.parseFrom(ProtoLiteUtils.java:241)
[23:24:36 WARN]: 	at shulker-server-agent-0.3.0-paper.jar//io.grpc.protobuf.lite.ProtoLiteUtils$MessageMarshaller.parse(ProtoLiteUtils.java:233)
[23:24:36 WARN]: 	at shulker-server-agent-0.3.0-paper.jar//io.grpc.protobuf.lite.ProtoLiteUtils$MessageMarshaller.parse(ProtoLiteUtils.java:130)
[23:24:36 WARN]: 	at shulker-server-agent-0.3.0-paper.jar//io.grpc.MethodDescriptor.parseResponse(MethodDescriptor.java:284)
[23:24:36 WARN]: 	at shulker-server-agent-0.3.0-paper.jar//io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1MessagesAvailable.runInternal(ClientCallImpl.java:667)
[23:24:36 WARN]: 	at shulker-server-agent-0.3.0-paper.jar//io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1MessagesAvailable.runInContext(ClientCallImpl.java:654)
[23:24:36 WARN]: 	... 5 more
[23:24:36 INFO]: Running delayed init tasks
[23:24:36 INFO]: Done (14.070s)! For help, type "help"
[23:24:36 INFO]: Timings Reset
2023/11/10 23:24:36 Stopping with rcon-cli
{"gsKey":"apps/vanilla-7kn7m-25tl4","message":"SDK server shutdown requested, waiting for game server shutdown","severity":"info","source":"*sdkserver.SDKServer","state":"Shutdown","time":"2023-11-10T23:24:36.233145205Z"}
{"message":"Shutting down SDK server","severity":"info","source":"main","time":"2023-11-10T23:24:36.233199685Z"}
{"error":"http: Server closed","message":"http server closed","severity":"info","source":"main","time":"2023-11-10T23:24:36.233257045Z"}
2023-11-10T23:24:36.260Z	ERROR	mc-server-runner	Failed to stop using rcon-cli	{"error": "exit status 1"}
2023-11-10T23:24:36.260Z	INFO	mc-server-runner	Sending 'stop' to Minecraft server...
2023-11-10T23:24:36.260Z	INFO	mc-server-runner	Waiting for completion...
[23:24:36 INFO]: Stopping the server
[23:24:36 INFO]: Stopping server
[23:24:36 INFO]: [ShulkerServerAgent] Disabling ShulkerServerAgent v0.3.0
[23:24:36 ERROR]: Error occurred (in the plugin loader) while disabling ShulkerServerAgent v0.3.0 (Is it up to date?)
kotlin.UninitializedPropertyAccessException: lateinit property healthcheckTask has not been initialized
	at io.shulkermc.serveragent.ShulkerServerAgentCommon.onServerShutdown(ShulkerServerAgentCommon.kt:61) ~[shulker-server-agent-0.3.0-paper.jar:?]
	at io.shulkermc.serveragent.paper.ShulkerServerAgentPaper.onDisable(ShulkerServerAgentPaper.kt:15) ~[shulker-server-agent-0.3.0-paper.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:283) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.disablePlugin(PaperPluginInstanceManager.java:224) ~[paper-1.20.2.jar:git-Paper-280]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.disablePlugins(PaperPluginInstanceManager.java:148) ~[paper-1.20.2.jar:git-Paper-280]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.disablePlugins(PaperPluginManagerImpl.java:92) ~[paper-1.20.2.jar:git-Paper-280]
	at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:528) ~[paper-api-1.20.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_20_R2.CraftServer.disablePlugins(CraftServer.java:575) ~[paper-1.20.2.jar:git-Paper-280]
	at net.minecraft.server.MinecraftServer.stopServer(MinecraftServer.java:930) ~[paper-1.20.2.jar:git-Paper-280]
	at net.minecraft.server.dedicated.DedicatedServer.stopServer(DedicatedServer.java:820) ~[paper-1.20.2.jar:git-Paper-280]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1195) ~[paper-1.20.2.jar:git-Paper-280]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315) ~[paper-1.20.2.jar:git-Paper-280]
	at java.lang.Thread.run(Unknown Source) ~[?:?]
[23:24:36 INFO]: Saving players
[23:24:36 INFO]: Saving worlds
[23:24:36 INFO]: Saving chunks for level 'ServerLevel[world]'/minecraft:overworld
[23:24:36 INFO]: [ChunkHolderManager] Waiting 60s for chunk system to halt for world 'world'
[23:24:36 INFO]: [ChunkHolderManager] Halted chunk system for world 'world'
[23:24:36 INFO]: [ChunkHolderManager] Saving all chunkholders for world 'world'
[23:24:38 INFO]: [ChunkHolderManager] Saved 1521 block chunks, 1 entity chunks, 0 poi chunks in world 'world' in 1.14s
[23:24:38 INFO]: ThreadedAnvilChunkStorage (world): All chunks are saved
2023-11-10 23:24:38,092 Log4j2-AsyncAppenderEventDispatcher-1-Async WARN Advanced terminal features are not available in this environment
[23:24:38 INFO]: ThreadedAnvilChunkStorage: All dimensions are saved
[23:24:38 INFO]: Flushing Chunk IO
[23:24:38 INFO]: Closing Thread Pool
[23:24:38 INFO]: Closing Server
2023-11-10T23:24:38.477Z	INFO	mc-server-runner	Done
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jeremylvln** [comment]
Renovate bumped a library which created this issue. It seems that I've fixed it. It does not crash anymore on my end. Sorry about that.
