### ISSUE TITLE
error: unexpected argument '--agones-allocation-tls-client-crt' found

### ISSUE THREAD

**Issue by TropicLegend** [jeremylvln/Shulker#245]
### What happened?

Getting this error when using the stock helm values.yaml: 
(error: unexpected argument '--agones-allocation-tls-client-crt' found)

This causes the pod [shulker-shulker-operator-655f76fffb-7cn56] to not start up.

```
error: unexpected argument '--agones-allocation-tls-client-crt' found

2023-11-26T18:59:37.260191685Z   tip: a similar argument exists: '--agones-allocator-tls-client-crt'

Usage: shulker-operator <--metrics-bind-address <address>|--api-bind-address <address>|--agones-allocator-host <host>|--agones-allocator-grpc-port <port>|--agones-allocator-tls-client-crt <path>|--agones-allocator-tls-client-key <path>>
2023-11-26T18:59:37.260203665Z 
For more information, try '--help'.
```

### Version

0.3.0

### Kubernetes Version

1.24

### Relevant log output

```Shell
error: unexpected argument '--agones-allocation-tls-client-crt' found

2023-11-26T18:59:37.260191685Z   tip: a similar argument exists: '--agones-allocator-tls-client-crt'

Usage: shulker-operator <--metrics-bind-address <address>|--api-bind-address <address>|--agones-allocator-host <host>|--agones-allocator-grpc-port <port>|--agones-allocator-tls-client-crt <path>|--agones-allocator-tls-client-key <path>>
2023-11-26T18:59:37.260203665Z 
For more information, try '--help'.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by TropicLegend** [comment]
I followed [this tutorial](https://shulker.jeremylvln.fr/guide/getting-started/installation.html).
And used the Helm installation method.

**Comment by jeremylvln** [comment]
Hi @TropicLegend.
Very sorry for this not-so-good onboarding to Shulker. It's clearly my bad!

The docs website is showing the fresh changes and not the latest published version. So there are some drifts. My bad on that, I'm stil working on the workflow to avoid that in the future.

You should be able to deploy Shulker using the "old" Kustomize-way: https://github.com/jeremylvln/Shulker/tree/72cd61f21b92e8539c0ed3daf656da6d3871d0e3/kube

I'm working on doing the real release that will work with Helm very shortly. I'll make sure to ping you when it's done :)

**Comment by TropicLegend** [comment]
Is there some documentation on how to do it the Kustomize-way? 
I got some errors related to the CRDs seemingly not being installed even though I did.

Since that release is already a month old, I think it makes more sense to just wait for the real release :+1: .
Thank you very much!

**Comment by Neeptossss** [comment]
I managed to get the operator running with helm (by removing the mtlsSecretName in value.yaml), everything seems to be working so far from the tutorial except when creating the MinecraftServerFleet. The pod seems to be looping in a crash caused by the shulker-server-agent.

The ShulkerServerAgent failed to be enabled then the server receive a shutdown via RCON-cli. I tried to get logs from the pod before it crashes here is what I got so far :

**Relevant log output**
```log
[init] Running as uid=1000 gid=1000 with /data as 'drwxrwxrwx 2 0 0 4096 Nov 27 22:08 /data'
[init] Resolving type given PAPER
[mc-image-helper] 22:08:21.707 INFO  : Resolved paper to version 1.20.1 build 196
[mc-image-helper] 22:08:26.011 INFO  : Downloaded /data/paper-1.20.1-196.jar
[init] Copying any configs from /config to /data
[mc-image-helper] 22:08:28.620 INFO  : Interpolating /config/server.properties -> /data/server.properties
[mc-image-helper] 22:08:28.622 INFO  : Interpolating /config/bukkit.yml -> /data/bukkit.yml
[mc-image-helper] 22:08:28.623 INFO  : Copying /config/plugins/shulker-server-agent-0.3.0-paper.jar -> /data/plugins/shulker-server-agent-0.3.0-paper.jar
[mc-image-helper] 22:08:28.706 INFO  : Interpolating /config/config/paper-global.yml -> /data/config/paper-global.yml
[mc-image-helper] 22:08:28.707 INFO  : Interpolating /config/spigot.yml -> /data/spigot.yml
[init] Skipping setup of server.properties
[init] Replacing env variables in /data that match the prefix 'CFG_' ...
[init] Starting the Minecraft server...
Downloading mojang_1.20.1.jar
Applying patches
Starting org.bukkit.craftbukkit.Main
*** Warning, you've not updated in a while! ***
*** Please download a new build as per instructions from https://papermc.io/downloads/paper ***
System Info: Java 17 (OpenJDK 64-Bit Server VM 17.0.8.1+1) Host: Linux 5.15.49-linuxkit (aarch64)
Loading libraries, please wait...
2023-11-27 22:08:43,648 ServerMain WARN Advanced terminal features are not available in this environment
[22:08:50 INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[22:08:50 INFO]: Found new data pack file/bukkit, loading it automatically
[22:08:52 INFO]: Loaded 7 recipes
[22:08:54 INFO]: Starting minecraft server version 1.20.1
[22:08:54 INFO]: Loading properties
[22:08:54 INFO]: This server is running Paper version git-Paper-196 (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: 773dd72)
[22:08:54 INFO]: Server Ping Player Sample Count: 12
[22:08:54 INFO]: Using 4 threads for Netty based IO
[22:08:54 INFO]: [ChunkTaskScheduler] Chunk system is using 1 I/O threads, 1 worker threads, and gen parallelism of 1 threads
[22:08:54 WARN]: [!] The timings profiler has been enabled but has been scheduled for removal from Paper in the future.
    We recommend installing the spark profiler as a replacement: https://spark.lucko.me/
    For more information please visit: https://github.com/PaperMC/Paper/issues/8948
[22:08:55 INFO]: Default game type: SURVIVAL
[22:08:55 INFO]: Generating keypair
[22:08:55 INFO]: Starting Minecraft server on *:25565
[22:08:55 INFO]: Using epoll channel type
[22:08:55 INFO]: Paper: Using libdeflate (Linux aarch64) compression from Velocity.
[22:08:55 INFO]: Paper: Using OpenSSL 1.1.x (Linux aarch64) cipher from Velocity.
[22:08:55 INFO]: [ShulkerServerAgent] Loading server plugin ShulkerServerAgent v0.3.0
[22:08:55 WARN]: **** SERVER IS RUNNING IN OFFLINE/INSECURE MODE!
[22:08:55 WARN]: The server will make no attempt to authenticate usernames. Beware.
[22:08:55 WARN]: Whilst this makes it possible to use Velocity, unless access to your server is properly restricted, it also opens up the ability for hackers to connect with any username they choose.
[22:08:55 WARN]: Please see https://docs.papermc.io/velocity/security for further information.
[22:08:55 WARN]: To change this, set "online-mode" to "true" in the server.properties file.
[22:08:55 INFO]: Preparing level "world"
[22:09:05 INFO]: Preparing start region for dimension minecraft:overworld
[22:09:05 INFO]: Time elapsed: 259 ms
[22:09:05 INFO]: [ShulkerServerAgent] Enabling ShulkerServerAgent v0.3.0
[22:09:09 INFO]: [ShulkerServerAgent] Identified Shulker server: qraft-cluster/lobby-dg985-tsh9t
[22:09:10 ERROR]: Error occurred while enabling ShulkerServerAgent v0.3.0 (Is it up to date?)
java.lang.ExceptionInInitializerError: null
 at io.shulkermc.serveragent.ShulkerServerAgentCommon.onServerInitialization(ShulkerServerAgentCommon.kt:42) ~[shulker-server-agent-0.3.0-paper.jar:?]
 at io.shulkermc.serveragent.paper.ShulkerServerAgentPaper.onEnable(ShulkerServerAgentPaper.kt:11) ~[shulker-server-agent-0.3.0-paper.jar:?]
 at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
 at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:189) ~[paper-1.20.1.jar:git-Paper-196]
 at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[paper-1.20.1.jar:git-Paper-196]
 at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
 at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugin(CraftServer.java:642) ~[paper-1.20.1.jar:git-Paper-196]
 at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugins(CraftServer.java:553) ~[paper-1.20.1.jar:git-Paper-196]
 at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:635) ~[paper-1.20.1.jar:git-Paper-196]
 at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:434) ~[paper-1.20.1.jar:git-Paper-196]
 at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:308) ~[paper-1.20.1.jar:git-Paper-196]
 at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1100) ~[paper-1.20.1.jar:git-Paper-196]
 at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.20.1.jar:git-Paper-196]
 at java.lang.Thread.run(Unknown Source) ~[?:?]
Caused by: java.lang.IllegalArgumentException: Invalid UUID string: 
 at java.util.UUID.fromString1(Unknown Source) ~[?:?]
 at java.util.UUID.fromString(Unknown Source) ~[?:?]
 at io.shulkermc.serveragent.Configuration.<clinit>(Configuration.kt:8) ~[shulker-server-agent-0.3.0-paper.jar:?]
 ... 14 more
[22:09:10 INFO]: [ShulkerServerAgent] Disabling ShulkerServerAgent v0.3.0
[22:09:10 INFO]: Running delayed init tasks
[22:09:10 INFO]: Done (16.908s)! For help, type "help"
[22:09:10 INFO]: Timings Reset
```

**Comment by jeremylvln** [comment]
I might have an idea of the issue, I'll fix :)
I plan to release today, just some finishing touches to make (including this bug fix)

**Comment by jeremylvln** [comment]
Hi @TropicLegend & @Neeptossss!

I just release a new version that seems to work correctly on my side. Do not hesitate to give me feedbacks, if you encounter anything I will work fixing these issues quickly.

I've updated the doc accordingly, pay attention to some modification you need to make to Agones: https://shulker.jeremylvln.fr/latest/guide/getting-started/prerequisites.html#mandatory-softwares

**Comment by Neeptossss** [comment]
Hi, huge thanks for this quick fix, everything seems to be working on my side !

Thanks you ! :)

**Comment by TropicLegend** [comment]
> Hi @TropicLegend & @Neeptossss!
> 
> 
> 
> I just release a new version that seems to work correctly on my side. Do not hesitate to give me feedbacks, if you encounter anything I will work fixing these issues quickly.
> 
> 
> 
> I've updated the doc accordingly, pay attention to some modification you need to make to Agones: https://shulker.jeremylvln.fr/latest/guide/getting-started/prerequisites.html#mandatory-softwares
> 
> 
> 
> Thanks again :)

Thank you very much for your quick fixes. I will look into it and try it out later today 👍

**Comment by TropicLegend** [comment]
Awesome, it works on my side as well :+1:
