### ISSUE TITLE
Proxy Crashes if no minecraft server is available at the moment

### ISSUE THREAD

**Issue by TropicLegend** [jeremylvln/Shulker#264]
### What happened?

If there is no MinecraftServer or MinecraftServerFleet deployed, the proxy crashes with the following error.
(Using "next")
Steps to reproduce:
Deploying: Cluster.yaml and proxy.yaml but not a minecraftServerFleet.
Then Proxy crashes.
At least I think this is what is related to the error I got.

I was able to fix it by deleting all of the resources and deploying the Cluster, the minecraft server fleet and the proxy.

### Version

0.4.0

### Kubernetes Version

1.24

### Relevant log output

```Shell
[init] Resolving type given VELOCITY
[init] Downloading https://papermc.io/api/v2/projects/velocity/versions/3.2.0-SNAPSHOT/builds/296/downloads/velocity-3.2.0-SNAPSHOT-296.jar
[mc-image-helper] 20:17:12.402 INFO  : Downloaded /server/velocity-3.2.0-SNAPSHOT-296.jar
[init] Setting initial memory to 512m and max to 512m
WARN StatusConsoleListener Advanced terminal features are not available in this environment
[20:17:13 INFO]: Booting up Velocity 3.2.0-SNAPSHOT (git-07a525be-b296)...
[20:17:13 INFO]: Loading localizations...
[20:17:13 INFO]: Connections will use epoll channels, libdeflate (Linux x86_64) compression, OpenSSL 1.1.x (Linux x86_64) ciphers
[20:17:13 INFO]: Loading plugins...
[20:17:13 INFO]: Loaded plugin shulker-proxy-agent 0.4.0 by Jérémy Levilain <jeremy@jeremylvln.fr>
[20:17:13 INFO]: Loaded 1 plugins
[20:17:14 INFO] [io.shulkermc.proxyagent.velocity.ShulkerProxyAgentVelocity]: Identified Shulker proxy: minecraft-network/public-9ds7k-5rljv
[20:17:14 ERROR] [io.shulkermc.proxyagent.velocity.ShulkerProxyAgentVelocity]: Shulker Agent crashed, stopping proxy
[20:17:14 ERROR]: redis.clients.jedis.exceptions.JedisConnectionException: Failed to connect to any host resolved for DNS name.
[20:17:14 ERROR]: 	at redis.clients.jedis.DefaultJedisSocketFactory.connectToFirstSuccessfulHost(DefaultJedisSocketFactory.java:63)
[20:17:14 ERROR]: 	at redis.clients.jedis.DefaultJedisSocketFactory.createSocket(DefaultJedisSocketFactory.java:87)
[20:17:14 ERROR]: 	at redis.clients.jedis.Connection.connect(Connection.java:195)
[20:17:14 ERROR]: 	at redis.clients.jedis.Connection.initializeFromClientConfig(Connection.java:393)
[20:17:14 ERROR]: 	at redis.clients.jedis.Connection.<init>(Connection.java:68)
[20:17:14 ERROR]: 	at redis.clients.jedis.Jedis.<init>(Jedis.java:220)
[20:17:14 ERROR]: 	at redis.clients.jedis.JedisFactory.makeObject(JedisFactory.java:170)
[20:17:14 ERROR]: 	at org.apache.commons.pool2.impl.GenericObjectPool.create(GenericObjectPool.java:571)
[20:17:14 ERROR]: 	at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:298)
[20:17:14 ERROR]: 	at org.apache.commons.pool2.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:223)
[20:17:14 ERROR]: 	at redis.clients.jedis.util.Pool.getResource(Pool.java:38)
[20:17:14 ERROR]: 	at redis.clients.jedis.JedisPool.getResource(JedisPool.java:378)
[20:17:14 ERROR]: 	at io.shulkermc.proxyagent.ShulkerProxyAgentCommon.onProxyInitialization(ShulkerProxyAgentCommon.kt:60)
[20:17:14 ERROR]: 	at io.shulkermc.proxyagent.velocity.ShulkerProxyAgentVelocity.onProxyInitialization(ShulkerProxyAgentVelocity.kt:30)
[20:17:14 ERROR]: 	at io.shulkermc.proxyagent.velocity.Lmbda$1.execute(Unknown Source)
[20:17:14 ERROR]: 	at com.velocitypowered.proxy.event.UntargetedEventHandler$VoidHandler.lambda$buildHandler$0(UntargetedEventHandler.java:56)
[20:17:14 ERROR]: 	at com.velocitypowered.proxy.event.VelocityEventManager.fire(VelocityEventManager.java:597)
[20:17:14 ERROR]: 	at com.velocitypowered.proxy.event.VelocityEventManager.lambda$fire$5(VelocityEventManager.java:478)
[20:17:14 ERROR]: 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[20:17:14 ERROR]: 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[20:17:14 ERROR]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[20:17:14 ERROR]: 	Suppressed: java.net.ConnectException: Connection refused
[20:17:14 ERROR]: 		at java.base/sun.nio.ch.Net.pollConnect(Native Method)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jeremylvln** [comment]
Hi!

I think this crash is due to Redis not being available. As you said that you just created the cluster it makes sense as Redis can take some time to start and be available. In this case I think your proxy started way faster than Redis, which explains why the DNS resolution failed: Kubernetes adds a `Pod` into a `Service` only when it's available, here Redis was not.

When your proxy will reboot the 2nd time (and if Redis is up), the issue should disappear :)

**Comment by TropicLegend** [comment]
oooh, okay. Thank you for elaborating :+1:
