### ISSUE TITLE
`Shulker Agent crashed, stopping proxy` after server is added to proxy

### ISSUE THREAD

**Issue by ajh123** [jeremylvln/Shulker#626]
### What happened?

When the Velocity proxy (with or without none Shulker plugins) starts up it loads the Shulker Agent, then gets identified, then tries to add the server - but the Shulker agent crashes.

At first I thought it was my Minestom agent implmentation, but when I used a normal Paper 1.21 server, the same proxy crash occurs.

Specifically, there is an `Index 0 out of bounds for length 0` error thrown from this line https://github.com/jeremylvln/Shulker/blob/f13ab898a2297e1a619fa267b25f486b5cf2306e/packages/shulker-proxy-agent/src/common/kotlin/io/shulkermc/proxyagent/adapters/kubernetes/ImplKubernetesGatewayAdapter.kt#L67

On version 0.8.1 I did not get this error.

### What components are involved in your issue?

Proxy Agent (Velocity)

### Version

0.9.0

### Kubernetes Version

Client Version: v1.30.4+k3s1 | Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3 | Server Version: v1.30.4+k3s1

### Relevant log output

```Shell
$ kubectl logs public-mdz42-fd8lk -n miners-online -f
[init] Resolving type given VELOCITY
[mc-image-helper] 18:46:12.252 INFO  : Downloaded /server/velocity-3.3.0-SNAPSHOT-416.jar
[init] Setting initial memory to 512m and max to 512m
WARN StatusConsoleListener Advanced terminal features are not available in this environment
[18:46:13 INFO]: Booting up Velocity 3.3.0-SNAPSHOT (git-6100e675-b416)...
[18:46:13 INFO]: Loading localizations...
[18:46:13 INFO]: Connections will use epoll channels, libdeflate (Linux x86_64) compression, OpenSSL 3.0.x (Linux x86_64) ciphers
[18:46:13 INFO]: Loading plugins...
[18:46:13 ERROR]: Can't load plugin viarewind due to missing dependency viabackwards
[18:46:13 INFO]: Loaded plugin mapmodcompanion 0.10.0 by turikhay
[18:46:13 INFO]: Loaded plugin shulker-proxy-agent 0.9.0 by Jérémy Levilain <jeremy@jeremylvln.fr>
[18:46:13 INFO]: Loaded plugin vpacketevents 1.1.0 by 4drian3d
[18:46:13 INFO]: Loaded plugin signedvelocity 1.2.4 by 4drian3d
[18:46:13 INFO]: Loaded plugin viaversion 5.0.4-SNAPSHOT by _MylesC, creeper123123321, Gerrygames, kennytv, Matsv, EnZaXD, RK_01
[18:46:13 INFO]: Loaded 5 plugins
[18:46:13 INFO] [mapmodcompanion]: Velocity and some of its plugins collect metrics and send them to bStats (https://bStats.org).
[18:46:13 INFO] [mapmodcompanion]: bStats collects some basic information for plugin authors, like how many people use
[18:46:13 INFO] [mapmodcompanion]: their plugin and their total player count. It's recommend to keep bStats enabled, but
[18:46:13 INFO] [mapmodcompanion]: if you're not comfortable with this, you can opt-out by editing the config.txt file in
[18:46:13 INFO] [mapmodcompanion]: the '/plugins/bStats/' folder and setting enabled to false.
[18:46:13 INFO] [mapmodcompanion]: Configuration has been loaded
[18:46:14 INFO] [io.shulkermc.proxyagent.velocity.ShulkerProxyAgentVelocity]: Identified Shulker proxy: miners-online/public-mdz42-fd8lk
[18:46:14 INFO] [io.shulkermc.proxyagent.velocity.ShulkerProxyAgentVelocity]: Added server 'lobby-lhmrz-hg4fx' to directory
[18:46:14 ERROR] [io.shulkermc.proxyagent.velocity.ShulkerProxyAgentVelocity]: Shulker Agent crashed, stopping proxy
java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
        at java.base/jdk.internal.util.Preconditions.outOfBounds(Unknown Source) ~[?:?]
        at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Unknown Source) ~[?:?]
        at java.base/jdk.internal.util.Preconditions.checkIndex(Unknown Source) ~[?:?]
        at java.base/java.util.Objects.checkIndex(Unknown Source) ~[?:?]
        at java.base/java.util.ArrayList.get(Unknown Source) ~[?:?]
        at io.shulkermc.proxyagent.adapters.kubernetes.ImplKubernetesGatewayAdapter.getFleetServiceAddress(ImplKubernetesGatewayAdapter.kt:67) ~[?:?]
        at io.shulkermc.proxyagent.services.PlayerMovementService.<init>(PlayerMovementService.kt:54) ~[?:?]
        at io.shulkermc.proxyagent.ShulkerProxyAgentCommon.onProxyInitialization(ShulkerProxyAgentCommon.kt:77) ~[?:?]
        at io.shulkermc.proxyagent.velocity.ShulkerProxyAgentVelocity.onProxyInitialization(ShulkerProxyAgentVelocity.kt:35) ~[?:?]
        at io.shulkermc.proxyagent.velocity.Lmbda$3.execute(Unknown Source) ~[?:?]
        at com.velocitypowered.proxy.event.UntargetedEventHandler$VoidHandler.lambda$buildHandler$0(UntargetedEventHandler.java:56) ~[velocity-3.3.0-SNAPSHOT-416.jar:3.3.0-SNAPSHOT (git-6100e675-b416)]
        at com.velocitypowered.proxy.event.VelocityEventManager.fire(VelocityEventManager.java:598) ~[velocity-3.3.0-SNAPSHOT-416.jar:3.3.0-SNAPSHOT (git-6100e675-b416)]
        at com.velocitypowered.proxy.event.VelocityEventManager.lambda$fire$5(VelocityEventManager.java:479) ~[velocity-3.3.0-SNAPSHOT-416.jar:3.3.0-SNAPSHOT (git-6100e675-b416)]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[?:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[?:?]
        at java.base/java.lang.Thread.run(Unknown Source) [?:?]
[18:46:14 INFO] [signedvelocity]: Starting SignedVelocity
[18:46:15 INFO] [viaversion]: Loading block connection mappings ...
[18:46:15 INFO] [viaversion]: Replacing channel initializers; you can safely ignore the following two warnings.
[18:46:15 WARN]: The server channel initializer has been replaced by java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(Unknown Source)
[18:46:15 WARN]: The backend channel initializer has been replaced by java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(Unknown Source)
[18:46:15 INFO] [viaversion]: ViaVersion detected lowest supported version by the proxy: 1.13 (393)
[18:46:15 INFO] [viaversion]: Highest supported version by the proxy: 1.21-1.21.1 (767)
[18:46:15 INFO] [viaversion]: Finished mapping loading, shutting down loader executor!
[18:46:15 INFO]: Listening on /[0:0:0:0:0:0:0:0%0]:25577
[18:46:15 INFO]: Done (2.04s)!
[18:46:15 INFO] [viaversion]: You are running a development version of the plugin, please report any bugs to GitHub.
[18:47:18 INFO]: Shutting down the proxy...
[18:47:18 INFO]: Closing endpoint /0.0.0.0:25577
[18:47:18 INFO] [io.shulkermc.proxyagent.velocity.ShulkerProxyAgentVelocity]: Trying to reconnect everyone to cluster
[18:47:18 WARN] [io.shulkermc.proxyagent.velocity.ShulkerProxyAgentVelocity]: Failed to reconnect everyone to cluster, connected players will be disconnected
kotlin.UninitializedPropertyAccessException: lateinit property playerMovementService has not been initialized
        at io.shulkermc.proxyagent.ShulkerProxyAgentCommon.getPlayerMovementService(ShulkerProxyAgentCommon.kt:43) ~[?:?]
        at io.shulkermc.proxyagent.ShulkerProxyAgentCommon.shutdown(ShulkerProxyAgentCommon.kt:114) ~[?:?]
        at io.shulkermc.proxyagent.ShulkerProxyAgentCommon.onProxyShutdown(ShulkerProxyAgentCommon.kt:106) ~[?:?]
        at io.shulkermc.proxyagent.velocity.ShulkerProxyAgentVelocity.onProxyShutdown(ShulkerProxyAgentVelocity.kt:47) ~[?:?]
        at io.shulkermc.proxyagent.velocity.Lmbda$4.execute(Unknown Source) ~[?:?]
        at com.velocitypowered.proxy.event.UntargetedEventHandler$VoidHandler.lambda$buildHandler$0(UntargetedEventHandler.java:56) ~[velocity-3.3.0-SNAPSHOT-416.jar:3.3.0-SNAPSHOT (git-6100e675-b416)]
        at com.velocitypowered.proxy.event.VelocityEventManager.fire(VelocityEventManager.java:598) ~[velocity-3.3.0-SNAPSHOT-416.jar:3.3.0-SNAPSHOT (git-6100e675-b416)]
        at com.velocitypowered.proxy.event.VelocityEventManager.lambda$fire$5(VelocityEventManager.java:479) ~[velocity-3.3.0-SNAPSHOT-416.jar:3.3.0-SNAPSHOT (git-6100e675-b416)]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[?:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[?:?]
        at java.base/java.lang.Thread.run(Unknown Source) [?:?]
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jeremylvln** [comment]
Hi. Looking into this right now, this is really weird

**Comment by ajh123** [comment]
Tanks! Also,

Since there is no relevant sections in the form here are my YAML configurations:

**cluster.yaml**:

```yaml
apiVersion: shulkermc.io/v1alpha1
kind: MinecraftCluster
metadata:
  name: miners-online-main
spec:
  networkAdmins:
    - c3e994d7-7699-4264-a3a7-5f0342a961dc
```

**proxy.yaml**:

```yaml
apiVersion: shulkermc.io/v1alpha1
kind: ProxyFleet
metadata:
  name: public
spec:
  clusterRef:
    name: miners-online-main
  replicas: 1
  service:
    type: LoadBalancer
    externalTrafficPolicy: Local
  template:
    spec:
      version:
        channel: Velocity
        name: latest
      config: #{}
        plugins:
          - url: http://10.0.0.160:83/proxy/plugins/MapModCompanion.jar
          - url: http://10.0.0.160:83/proxy/plugins/SignedVelocity-Proxy-1.2.4.jar
          - url: http://10.0.0.160:83/proxy/plugins/ViaRewind-4.0.3-SNAPSHOT.jar
          - url: http://10.0.0.160:83/proxy/plugins/ViaVersion-5.0.4-SNAPSHOT.jar
          - url: http://10.0.0.160:83/proxy/plugins/VPacketEvents-1.1.0.jar
```

**lobby.yaml**: (the comments were my previous config)

```yaml
apiVersion: shulkermc.io/v1alpha1
kind: MinecraftServerFleet
metadata:
  name: lobby
spec:
  clusterRef:
    name: miners-online-main
  replicas: 1
  template:
    spec:
      clusterRef:
        name: miners-online-main
      tags:
        - lobby
      version:
        channel: Paper
        name: '1.21'
#        customJar:
#          url: http://10.0.0.160:83/lobby/Lobby-1.0-SNAPSHOT-all.jar
      config: {}
#      config:
#        world:
#          url: http://10.0.0.160:83/lobby/Lobby.tar.gz
#        serverProperties:
#          level-name: Lobby
#          level-spawn-x: '8.5'
#          level-spawn-y: '100.5'
#          level-spawn-z: '8.5'
#          server-ip: '127.0.0.1'
#          server-port: '25565'
```

**Comment by jeremylvln** [comment]
Would you mind sharing your Kubernetes Service? It should be named `public`. I bet that you do not have any IP listed in the `.status.loadbalancer.ingress` field. I was expecting that there would be always one, but I was sooo wrong.

I fixed this in the linked PR by doing two things:
1. I now properly check that there is an address, without any assumption
2. I'm now watching the Service to handle external updates that may change the IP

I'll merge this tomorrow to give me a bit of time to check, but I'll likely ask you to verify on your end the fix before releasing if you are good with that.

**Comment by ajh123** [comment]
Thanks for the quick update,

> Would you mind sharing your Kubernetes Service? It should be named `public`. I bet that you do not have any IP listed in the `.status.loadbalancer.ingress` field. I was expecting that there would be always one, but I was sooo wrong.

I'm a beginner to using Kubernetes, would you mind sharing how I can do that?

> I'll merge this tomorrow to give me a bit of time to check, but I'll likely ask you to verify on your end the fix before releasing if you are good with that.

Yes, I can.

**Comment by ajh123** [comment]
I think I've found the command.

```
$ kubectl get svc --all-namespaces
NAMESPACE        NAME                                      TYPE           CLUSTER-IP      EXTERNAL-IP   PORT(S)                      AGE
agones-system    agones-allocator                          LoadBalancer   10.43.148.70    <pending>     443:30350/TCP                20h
agones-system    agones-allocator-metrics-service          ClusterIP      10.43.211.154   <none>        8080/TCP                     20h
agones-system    agones-controller-metrics-service         ClusterIP      10.43.144.5     <none>        8080/TCP                     20h
agones-system    agones-controller-service                 ClusterIP      10.43.224.62    <none>        443/TCP,8080/TCP             20h
agones-system    agones-extensions-metrics-service         ClusterIP      10.43.68.229    <none>        8080/TCP                     20h
agones-system    agones-ping-http-service                  LoadBalancer   10.43.82.200    <pending>     80:32180/TCP                 20h
agones-system    agones-ping-udp-service                   LoadBalancer   10.43.46.221    10.0.0.109    50000:30257/UDP              20h
default          kubernetes                                ClusterIP      10.43.0.1       <none>        443/TCP                      20h
kube-system      kube-dns                                  ClusterIP      10.43.0.10      <none>        53/UDP,53/TCP,9153/TCP       20h
kube-system      metrics-server                            ClusterIP      10.43.45.169    <none>        443/TCP                      20h
kube-system      traefik                                   LoadBalancer   10.43.135.157   10.0.0.109    80:32471/TCP,443:30617/TCP   20h
miners-online    miners-online-main-cluster                ClusterIP      None            <none>        <none>                       2m27s
miners-online    miners-online-main-redis-managed          ClusterIP      10.43.17.151    <none>        6379/TCP                     2m27s
miners-online    public                                    LoadBalancer   10.43.52.216    10.0.0.109    25565:31051/TCP              2m22s
shulker-system   shulker-system-shulker-operator           ClusterIP      10.43.10.98     <none>        9090/TCP                     19h
shulker-system   shulker-system-shulker-operator-metrics   ClusterIP      10.43.94.230    <none>        8080/TCP                     19h
```

It looks like the `public` `LoadBalancer` service does have internal and external IPs.

**Comment by ajh123** [comment]
Also, `kubectl describe svc public -n miners-online` shows:

```
Name:                     public
Namespace:                miners-online
Labels:                   app.kubernetes.io/component=proxy
                          app.kubernetes.io/instance=proxy-public
                          app.kubernetes.io/managed-by=shulker-operator
                          app.kubernetes.io/name=proxy
                          app.kubernetes.io/part-of=cluster-miners-online-main
                          minecraftcluster.shulkermc.io/name=miners-online-main
                          proxyfleet.shulkermc.io/name=public
Annotations:              <none>
Selector:                 app.kubernetes.io/component=proxy,app.kubernetes.io/instance=proxy-public,app.kubernetes.io/managed-by=shulker-operator,app.kubernetes.io/name=proxy,app.kubernetes.io/part-of=cluster-miners-online-main,minecraftcluster.shulkermc.io/name=miners-online-main,proxyfleet.shulkermc.io/name=public
Type:                     LoadBalancer
IP Family Policy:         SingleStack
IP Families:              IPv4
IP:                       10.43.52.216
IPs:                      10.43.52.216
LoadBalancer Ingress:     10.0.0.109
Port:                     minecraft  25565/TCP
TargetPort:               minecraft/TCP
NodePort:                 minecraft  31051/TCP
Endpoints:                10.42.0.229:25577
Session Affinity:         None
External Traffic Policy:  Local
HealthCheck NodePort:     30584
Events:
  Type     Reason                   Age                  From                   Message
  ----     ------                   ----                 ----                   -------
  Normal   EnsuringLoadBalancer     11m                  service-controller     Ensuring load balancer
  Normal   AppliedDaemonSet         11m                  service-lb-controller  Applied LoadBalancer DaemonSet kube-system/svclb-public-23248c2c
  Warning  UnAvailableLoadBalancer  65s (x7 over 9m57s)  service-lb-controller  There are no available nodes for LoadBalancer
  Normal   UpdatedLoadBalancer      34s (x8 over 10m)    service-lb-controller  Updated LoadBalancer with new IPs: [] -> [10.0.0.109]
```

**Comment by ajh123** [comment]
Some more weird behaviour:
`kubectl get svc public -o jsonpath='{.status.loadBalancer.ingress[0]}' -n miners-online` only returns correct data if I run `kubectl get svc public -o jsonpath='{.status.loadBalancer.ingress[1]}' -n miners-online` before it.

If I run `kubectl get svc public -o jsonpath='{.status.loadBalancer.ingress[0]}' -n miners-online` on its own I get nothing.

**Comment by ajh123** [comment]
Now after I've ran `kubectl get svc public -o jsonpath='{.status.loadBalancer.ingress[*]}' -n miners-online`, the `kubectl get svc public -o jsonpath='{.status.loadBalancer.ingress[0]}' -n miners-online` command now consistently returns data.

**Comment by ajh123** [comment]
One possible explanation is that the proxy is crashing and restarting during each command.

**Comment by jeremylvln** [comment]
Do you install Shulker with Helm? If yes, add this to your `values.yaml` file to use the `next` version of Shulker which contains the fix alongside the fixed agent plugin:

```yaml
operator:
  image:
    tag: next

  extraArgs:
    - --agent-maven-repository=https://maven.jeremylvln.fr/artifactory/shulker-snapshots
    - --agent-version=0.9.0-SNAPSHOT
```

Let me know if it fixes your issue, on my side I confirmed it worked fine.

It's really weird that your LB IP is changing that much, it should just be assigned once and then not change. It may be a special behavior of your LB controller, depending on your Kubernetes setup (on-promise / cloud provider).

**Comment by ajh123** [comment]
@jeremylvln

Can confirm the issues has been fixed. Not sure what is causing the inconstant IPs of the LB but it's not causing significant issues.

**Comment by jeremylvln** [comment]
Great! I started a fix release
