### ISSUE TITLE
Shulker Agent crashed getIp null

### ISSUE THREAD

**Issue by NathaelB** [jeremylvln/Shulker#746]
### What happened?

I follow the documentation for create a cluster minecraft.

When I create my proxy, the pod not ready because in the container I have a error:

```
proxy [init] Resolving type given VELOCITY
proxy [mc-image-helper] 17:12:47.204 INFO  : Downloaded /server/velocity-3.4.0-SNAPSHOT-450.jar
proxy [init] Setting initial memory to 512m and max to 512m
proxy 2024-11-15T17:12:47.794364628Z main WARN Advanced terminal features are not available in this environment
proxy [17:12:47 INFO]: Booting up Velocity 3.4.0-SNAPSHOT (git-cefa3b27-b450)...
proxy [17:12:47 INFO]: Loading localizations...
proxy [17:12:48 INFO]: Connections will use epoll channels, libdeflate (Linux aarch64) compression, OpenSSL 3.x.x (Linux aarch64) ciphers
proxy [17:12:48 INFO]: Loading plugins...
proxy [17:12:48 INFO]: Loaded plugin shulker-proxy-agent 0.11.0 by Jérémy Levilain <jeremy@jeremylvln.fr>
proxy [17:12:48 INFO]: Loaded 2 plugins
proxy [17:12:48 INFO] [io.shulkermc.proxyagent.velocity.ShulkerProxyAgentVelocity]: Identified Shulker proxy: default/public-vmmhs-h4qj4
proxy [17:12:48 INFO] [io.shulkermc.proxyagent.velocity.ShulkerProxyAgentVelocity]: Proxy will watch fleet's Service to extract external address
proxy [17:12:48 ERROR] [io.shulkermc.proxyagent.velocity.ShulkerProxyAgentVelocity]: Shulker Agent crashed, stopping proxy
proxy java.lang.NullPointerException: getIp(...) must not be null
proxy     at io.shulkermc.proxyagent.adapters.kubernetes.ImplKubernetesGatewayAdapter$getExternalAddressFromService$1.invoke(ImplKubernetesGatewayAdapter.kt:111) ~[?:?]
proxy     at io.shulkermc.proxyagent.adapters.kubernetes.ImplKubernetesGatewayAdapter$getExternalAddressFromService$1.invoke(ImplKubernetesGatewayAdapter.kt:111) ~[?:?]
proxy     at io.shulkermc.proxyagent.adapters.kubernetes.ImplKubernetesGatewayAdapter.getExternalAddressFromService$lambda$0(ImplKubernetesGatewayAdapter.kt:111) ~[?:?]
proxy     at java.base/java.util.Optional.map(Unknown Source) ~[?:?]
proxy     at io.shulkermc.proxyagent.adapters.kubernetes.ImplKubernetesGatewayAdapter.getExternalAddressFromService(ImplKubernetesGatewayAdapter.kt:111) ~[?:?]
proxy     at io.shulkermc.proxyagent.adapters.kubernetes.ImplKubernetesGatewayAdapter.getExternalAddress(ImplKubernetesGatewayAdapter.kt:57) ~[?:?]
proxy     at io.shulkermc.proxyagent.services.PlayerMovementService.<init>(PlayerMovementService.kt:73) ~[?:?]
proxy     at io.shulkermc.proxyagent.ShulkerProxyAgentCommon.onProxyInitialization(ShulkerProxyAgentCommon.kt:77) ~[?:?]
proxy     at io.shulkermc.proxyagent.velocity.ShulkerProxyAgentVelocity.onProxyInitialization(ShulkerProxyAgentVelocity.kt:35) ~[?:?]
proxy     at io.shulkermc.proxyagent.velocity.Lmbda$1.execute(Unknown Source) ~[?:?]
proxy     at com.velocitypowered.proxy.event.UntargetedEventHandler$VoidHandler.lambda$buildHandler$0(UntargetedEventHandler.java:56) ~[velocity-3.4.0-SNAPSHOT-450.jar:3.4.0-SNAPSHOT
(git-cefa3b27-b450)]
proxy     at com.velocitypowered.proxy.event.VelocityEventManager.fire(VelocityEventManager.java:676) ~[velocity-3.4.0-SNAPSHOT-450.jar:3.4.0-SNAPSHOT (git-cefa3b27-b450)]
proxy     at com.velocitypowered.proxy.event.VelocityEventManager.lambda$fire$5(VelocityEventManager.java:541) ~[velocity-3.4.0-SNAPSHOT-450.jar:3.4.0-SNAPSHOT (git-cefa3b27-b450)]
proxy     at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[?:?]
proxy     at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[?:?]
proxy     at java.base/java.lang.Thread.run(Unknown Source) [?:?]
proxy [17:12:48 INFO]: Listening on /[0:0:0:0:0:0:0:0]:25577
proxy [17:12:48 INFO]: Velocity and some of its plugins collect metrics and send them to bStats (https://bStats.org).
proxy [17:12:48 INFO]: bStats collects some basic information for plugin authors, like how many people use
proxy [17:12:48 INFO]: their plugin and their total player count. It's recommended to keep bStats enabled, but
proxy [17:12:48 INFO]: if you're not comfortable with this, you can opt-out by editing the config.txt file in
proxy [17:12:48 INFO]: the '/plugins/bStats/' folder and setting enabled to false.
proxy [17:12:48 INFO]: Done (0.89s)!
```

The shulker-operator logs 

```
{"timestamp":"2024-11-15T17:08:38.676088Z","level":"INFO","fields":{"message":"reconciling ProxyFleet","name":"public","namespace":"default"},"target":"shulker_operator::reconcilers::
proxy_fleet","span":{"name":"reconcile"},"spans":[{"object.reason":"related object updated: ConfigMap.v1./public-config.default","object.ref":"ProxyFleet.v1alpha1.shulkermc.io/public.
default","name":"reconciling object"},{"name":"reconcile"}]}
{"timestamp":"2024-11-15T17:08:38.691102Z","level":"INFO","fields":{"message":"reconciling ProxyFleet","name":"public","namespace":"default"},"target":"shulker_operator::reconcilers::
proxy_fleet","span":{"name":"reconcile"},"spans":[{"object.reason":"related object updated: ConfigMap.v1./public-config.default","object.ref":"ProxyFleet.v1alpha1.shulkermc.io/public.
default","name":"reconciling object"},{"name":"reconcile"}]}
{"timestamp":"2024-11-15T17:08:38.903117Z","level":"INFO","fields":{"message":"reconciling ProxyFleet","name":"public","namespace":"default"},"target":"shulker_operator::reconcilers::
proxy_fleet","span":{"name":"reconcile"},"spans":[{"object.reason":"related object updated: Fleet.v1.agones.dev/public.default","object.ref":"ProxyFleet.v1alpha1.shulkermc.io/public.d
efault","name":"reconciling object"},{"name":"reconcile"}]}
{"timestamp":"2024-11-15T17:08:38.923111Z","level":"INFO","fields":{"message":"reconciling ProxyFleet","name":"public","namespace":"default"},"target":"shulker_operator::reconcilers::
proxy_fleet","span":{"name":"reconcile"},"spans":[{"object.reason":"object updated","object.ref":"ProxyFleet.v1alpha1.shulkermc.io/public.default","name":"reconciling object"},{"name"
:"reconcile"}]}
{"timestamp":"2024-11-15T17:08:39.344918Z","level":"INFO","fields":{"message":"reconciling ProxyFleet","name":"public","namespace":"default"},"target":"shulker_operator::reconcilers::
proxy_fleet","span":{"name":"reconcile"},"spans":[{"object.reason":"related object updated: Fleet.v1.agones.dev/public.default","object.ref":"ProxyFleet.v1alpha1.shulkermc.io/public.d
efault","name":"reconciling object"},{"name":"reconcile"}]}
{"timestamp":"2024-11-15T17:08:39.370988Z","level":"INFO","fields":{"message":"reconciling ProxyFleet","name":"public","namespace":"default"},"target":"shulker_operator::reconcilers::
proxy_fleet","span":{"name":"reconcile"},"spans":[{"object.reason":"object updated","object.ref":"ProxyFleet.v1alpha1.shulkermc.io/public.default","name":"reconciling object"},{"name"
:"reconcile"}]}
{"timestamp":"2024-11-15T17:12:46.657490Z","level":"INFO","fields":{"message":"reconciling MinecraftCluster","name":"getting-started","namespace":"default"},"target":"shulker_operator
::reconcilers::minecraft_cluster","span":{"name":"reconcile"},"spans":[{"object.reason":"reconciler requested retry","object.ref":"MinecraftCluster.v1alpha1.shulkermc.io/getting-start
ed.default","name":"reconciling object"},{"name":"reconcile"}]}
{"timestamp":"2024-11-15T17:12:46.681535Z","level":"INFO","fields":{"message":"reconciling MinecraftCluster","name":"getting-started","namespace":"default"},"target":"shulker_operator
::reconcilers::minecraft_cluster","span":{"name":"reconcile"},"spans":[{"object.reason":"related object updated: Service.v1./getting-started-cluster.default","object.ref":"MinecraftCl
uster.v1alpha1.shulkermc.io/getting-started.default","name":"reconciling object"},{"name":"reconcile"}]}
{"timestamp":"2024-11-15T17:13:39.378128Z","level":"INFO","fields":{"message":"reconciling ProxyFleet","name":"public","namespace":"default"},"target":"shulker_operator::reconcilers::
proxy_fleet","span":{"name":"reconcile"},"spans":[{"object.reason":"reconciler requested retry","object.ref":"ProxyFleet.v1alpha1.shulkermc.io/public.default","name":"reconciling obje
ct"},{"name":"reconcile"}]}
```

The values are the same as those given in the documentation for kubernetes manifests.

### What components are involved in your issue?

Proxy Agent (Velocity)

### Version

0.11.0

### Kubernetes Version

1.30.2

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jeremylvln** [comment]
Could you provide me the Kubernetes `LoadBalancer` resource Shulker has created? Especially the `status` part (don't hesitate to mask out the IPs if some are listed, I just need to see the shape, not the values)

**Comment by NathaelB** [comment]
Good evening, I apologise for the delay I had disconnected for some time.

Here is a screen of all the services created on my k8s cluster:

<img width="1250" alt="image" src="https://github.com/user-attachments/assets/0fc1b480-b7b4-4549-b888-95baa19cad9d">
